// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: src/main/proto/races.proto

package race

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Races struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Races []*Race `protobuf:"bytes,1,rep,name=races,proto3" json:"races,omitempty"`
}

func (x *Races) Reset() {
	*x = Races{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_proto_races_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Races) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Races) ProtoMessage() {}

func (x *Races) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_proto_races_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Races.ProtoReflect.Descriptor instead.
func (*Races) Descriptor() ([]byte, []int) {
	return file_src_main_proto_races_proto_rawDescGZIP(), []int{0}
}

func (x *Races) GetRaces() []*Race {
	if x != nil {
		return x.Races
	}
	return nil
}

var File_src_main_proto_races_proto protoreflect.FileDescriptor

var file_src_main_proto_races_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x72, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2d, 0x69, 0x6f,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x61, 0x74, 0x78, 0x69, 0x62, 0x6f, 0x63,
	0x6f, 0x73, 0x2e, 0x70, 0x63, 0x73, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x72, 0x61, 0x63, 0x65, 0x1a, 0x19, 0x73, 0x72, 0x63,
	0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x05, 0x52, 0x61, 0x63, 0x65, 0x73, 0x12,
	0x49, 0x0a, 0x05, 0x72, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x61, 0x74, 0x78, 0x69,
	0x62, 0x6f, 0x63, 0x6f, 0x73, 0x2e, 0x70, 0x63, 0x73, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x52,
	0x61, 0x63, 0x65, 0x52, 0x05, 0x72, 0x61, 0x63, 0x65, 0x73, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x74, 0x78, 0x69, 0x62, 0x6f,
	0x63, 0x6f, 0x73, 0x2f, 0x70, 0x63, 0x73, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x72,
	0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_main_proto_races_proto_rawDescOnce sync.Once
	file_src_main_proto_races_proto_rawDescData = file_src_main_proto_races_proto_rawDesc
)

func file_src_main_proto_races_proto_rawDescGZIP() []byte {
	file_src_main_proto_races_proto_rawDescOnce.Do(func() {
		file_src_main_proto_races_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_main_proto_races_proto_rawDescData)
	})
	return file_src_main_proto_races_proto_rawDescData
}

var file_src_main_proto_races_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_main_proto_races_proto_goTypes = []interface{}{
	(*Races)(nil), // 0: io.github.patxibocos.pcsscraper.protobuf.race.Races
	(*Race)(nil),  // 1: io.github.patxibocos.pcsscraper.protobuf.race.Race
}
var file_src_main_proto_races_proto_depIdxs = []int32{
	1, // 0: io.github.patxibocos.pcsscraper.protobuf.race.Races.races:type_name -> io.github.patxibocos.pcsscraper.protobuf.race.Race
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_main_proto_races_proto_init() }
func file_src_main_proto_races_proto_init() {
	if File_src_main_proto_races_proto != nil {
		return
	}
	file_src_main_proto_race_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_main_proto_races_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Races); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_main_proto_races_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_main_proto_races_proto_goTypes,
		DependencyIndexes: file_src_main_proto_races_proto_depIdxs,
		MessageInfos:      file_src_main_proto_races_proto_msgTypes,
	}.Build()
	File_src_main_proto_races_proto = out.File
	file_src_main_proto_races_proto_rawDesc = nil
	file_src_main_proto_races_proto_goTypes = nil
	file_src_main_proto_races_proto_depIdxs = nil
}
